reporter: apiary
dry-run: null
hookfiles: null
language: php
sandbox: false
server: 'php -S 0.0.0.0:3000 -t web'
server-wait: 3
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: apiary.apib
endpoint: 'http://localhost:3000'
